version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: "Australia/Brisbane"
  groups:
    all: # group all the things
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: "Australia/Brisbane"
