services:
  maremma:
    image: ghcr.io/yaleman/maremma:latest
    container_name: maremma
    init: true
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /data
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
      - ./maremma.json:/data/maremma.json:ro
