---
name: Rust Testing
"on":
  push:
    paths-ignore:
      - docs/**
      - static/**
      - plugins/**
env:
  MAREMMA_FRONTEND_URL: "http://localhost:8080"
  MAREMMA_OIDC_CLIENT_ID: "http://localhost:8080"
  MAREMMA_OIDC_ISSUER: "http://github.com"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v4
      - name: Install typical dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libssl-dev
      - name: "Cargo coverage"
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --coveralls "${{ secrets.COVERALLS_REPO_TOKEN }}"
  cargo_test:
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v4
      - name: Install typical dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libssl-dev

      - name: "Run cargo test"
        run: cargo test
  build_release:
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: "Build the workspace"
        run: cargo build --workspace --release
